MiniProjekt/Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore;
using System.Data;

namespace MiniProjekt.Models
{
    public class ApplicationContext : DbContext
    {
        public ApplicationContext(DbContextOptions<ApplicationContext> options) :
            base(options)
        {
        }

        public DbSet<FoodItem> FoodItems { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<FoodItem>()
                .Property(o => o.ExpirationDate)
                .HasColumnType(SqlDbType.Date.ToString());
        }
    }
}

MiniProjekt/Models/DataService.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using MiniProjekt.Migrations;
using MiniProjekt.Views.eSpensa;

namespace MiniProjekt.Models
{
    public class DataService : IDataService
    {
        public DataService(ApplicationContext context)
        {
            Context = context;
        }

        public ApplicationContext Context;

        public async Task<IndexVM> GetIndexVM()
        {
            var expiringSoon = Context.FoodItems.Where(o => o.ExpirationDate.AddDays(-5) < DateTime.Now).Count();

            return new IndexVM { ExpiringSoon = expiringSoon, InMyShoppingListCount = 0 };
        }

        public MyFoodVM GetMyFoodVM()
        {
            int referencedate = DateOnly.FromDateTime(DateTime.Now).DayNumber;
            return new MyFoodVM
            {
                ItemsInFridgeCount = Context.FoodItems.Where(o => o.GoesInTheFridge).Count(),
                ItemsInPentryCount = Context.FoodItems.Where(o => !o.GoesInTheFridge).Count(),
                ConsumeSoon = Context.FoodItems.Where(o => o.ExpirationDate.AddDays(-5) < DateTime.Now).Count()
            };
        }

        public void AddFood(AddItemToMyFoodVM model)
        {
            Context.FoodItems.Add(new FoodItem
            {
                Name = model.Name,
                ExpirationDate = model.ExpirationDate,
                FoodGroup = model.FoodGroup,
                GoesInTheFridge = model.GoesInTheFridge,
            });
            Context.SaveChanges();
        }

        public FoodListVM GetFoodListVM(string listName)
        {
            var reference = DateTime.Now;
            var foodsInList = Context.FoodItems.Select(o => new FoodListVM.FoodItemVM
            {
                ItemName = o.Name,
                Id = o.Id,
                IsRefrigerated = o.GoesInTheFridge,
                FoodGroup = o.FoodGroup.ToString(),
                ExpirationDate = o.ExpirationDate,
            }).ToArray();

            switch (listName)
            {
                case "Fridge":
                    foodsInList = foodsInList.Where(o => o.IsRefrigerated).ToArray();
                    break;
                case "Pentry":
                    foodsInList = foodsInList.Where(o => !o.IsRefrigerated).ToArray();
                    break;
                case "Expiring":
                    foodsInList = foodsInList.Where(o => (o.ExpirationDate.AddDays(-5) < DateTime.Now)).ToArray();
                    break;
                case "All":  
                    break;
            }

            return new FoodListVM { Name = listName, FoodsList = foodsInList};
        }

        public void RemoveFoodItemByID(int id)
        {
            var toRemove = Context.FoodItems.Single(o => o.Id == id);
            Context.FoodItems.Remove(toRemove);
            Context.SaveChanges();
        }
    }
}

MiniProjekt/Models/FoodGroupEnum.cs
namespace MiniProjekt.Models
{
    public enum FoodGroupEnum
    {
        Dairy,
        Vegetable,
        Fruit,
        Meat,
        Fish,
        Spice,
        Condiment,
        Snack,
        Other
    }
}

MiniProjekt/Models/FoodItem.cs
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace MiniProjekt.Models
{
    public class FoodItem
    {
        public string Name { get; set; }
        public int Id { get; set; }

        public bool GoesInTheFridge { get; set; }

        public DateTime ExpirationDate { get; set; }

        public FoodGroupEnum FoodGroup { get; set; }
    }
}

MiniProjekt/Models/IDataService.cs
using MiniProjekt.Views.eSpensa;

namespace MiniProjekt.Models
{
    public interface IDataService
    {
        void AddFood(AddItemToMyFoodVM model);
        FoodListVM GetFoodListVM(string listName);
        Task<IndexVM> GetIndexVM();
        MyFoodVM GetMyFoodVM();
        void RemoveFoodItemByID(int id);
    }
}

MiniProjekt/Controllers/eSpensaController.cs
using Microsoft.AspNetCore.Mvc;
using MiniProjekt.Views.eSpensa;
using MiniProjekt.Models;

namespace MiniProjekt.Controllers
{
    public class eSpensaController : Controller
    {
        IDataService service;

        public eSpensaController(IDataService service)
        {
            this.service = service;
        }

        [HttpGet("")]
        [HttpGet("/Home")]
        public async Task<IActionResult> Index()
        {
            IndexVM model = await service.GetIndexVM();
            return View(model);
        }

        [HttpGet("/MyFood")]
        public IActionResult MyFood()
        {
            MyFoodVM model = service.GetMyFoodVM();
            return View(model);
        }

        [HttpGet("/MyFood/Add")]
        public IActionResult AddItemToMyFood()
        {
            return View();
        }

        [HttpPost("/MyFood/Add")]
        public IActionResult AddItemToMyFood(AddItemToMyFoodVM model)
        {
            if (!ModelState.IsValid)
                return View(model);
            else
            {
                service.AddFood(model);
                return RedirectToAction(nameof(MyFood));
            }
        }

        [HttpGet("/MyFood/{listName}")]
        public IActionResult FoodList(string listName)
        {
            FoodListVM model = service.GetFoodListVM(listName);
            return View(model);
        }

        [HttpGet("MyFood/{listName}/Delete/{id}")]
        public IActionResult DeleteFoodItem(int id, string listName)
        {
            service.RemoveFoodItemByID(id);
            return RedirectToAction(nameof(FoodList), new { listName = listName });
        }


        [HttpGet("/MyLists")]
        public IActionResult MyLists()
        {
            MyListsVM model = new MyListsVM
            {
                ListOfLists = new MyListsVM.ListVM[]
                {
                    new MyListsVM.ListVM { Name = "Placeholder", ItemCount = 4},
                    new MyListsVM.ListVM { Name = "Example", ItemCount = 2},
                    new MyListsVM.ListVM { Name = "Test", ItemCount = 6}
                }
            };
            return View(model);
        }

        [HttpGet("/MyLists/{id}")]
        public IActionResult List(string id)
        {
            ListVM model = new ListVM
            {
                Name = id,
                FoodsList = new ListVM.FoodItemVM[]
                {
                    new ListVM.FoodItemVM{ ItemName = "Bananas"},
                    new ListVM.FoodItemVM{ ItemName = "Milk"},
                    new ListVM.FoodItemVM{ ItemName = "Eggs" },
                }
            };
            return View(model);
        }

        [HttpGet("MyLists/Delete/{id}")]
        [HttpPost("MyLists/Delete/{id}")]
        public IActionResult DeleteList(string id)
        {
            return RedirectToAction(nameof(MyLists));
        }
    }
}

MiniProjekt/Views/Shared/_FoodItemInMyFood.cshtml
@model FoodListVM.FoodItemVM
@{
    int daysLeft = (Model.ExpirationDate - DateTime.Now.Date).Days;
 }

<li class="list-group-item d-flex @(Model.IsRefrigerated ? "list-group-item-primary" : "") justify-content-between align-items-start">
    <div class="ms-2 me-auto">
        <div class="fw-bold">@Model.ItemName</div>
        @Model.FoodGroup <a asp-action="DeleteFoodItem" asp-route-listName="@ViewBag.Title" asp-route-id="@Model.Id">Remove</a>
    </div>
    <span class="badge @(daysLeft < 3 ? "bg-danger" : "bg-primary") rounded-pill ">@(daysLeft + " " + ((uint)daysLeft == 1 ? "day" : "days")) left</span>
</li>

MiniProjekt/Views/Shared/_FoodItemInShoppingList.cshtml
@model ListVM.FoodItemVM

<li class="list-group-item">
    <div class="pl-4">
        <input class="form-check-input me-1" type="checkbox" value="" id="@Model.Id">
        <label class="form-check-label" for="@Model.Id">@Model.ItemName</label>
    </div>
</li>

MiniProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" charset="utf-8" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h2 class="display-4 text-center">eSpensa</h2>
    <div class="container mt-3">
        <article class="box">
            <partial name="_Navbar" />
            <div class="box text-center">
            @RenderBody()
            </div>
        </article>
    </div>
    <div class="mt-2 text-center">&copy; SandroNet Solutions 2023</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @RenderSection("scriptsJq", false)
</body>
</html>

MiniProjekt/Views/Shared/_ListItem.cshtml
@model MyListsVM.ListVM

<li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
        <div class="fw-bold">@Model.Name</div>
        <span>
            <a asp-action="List" asp-route-id=@Model.Name>View</a>
            <a asp-action="DeleteList" asp-route-id=@Model.Name>Delete</a>
        </span>
    </div>
    <span class="badge bg-primary rounded-pill" style="color: white;">@Model.ItemCount</span>
</li>

MiniProjekt/Views/Shared/_Navbar.cshtml
<nav class="nav justify-content-center mb-3">
    <a class="nav-link" asp-controller="eSpensa" asp-action="Index">Home</a>
    <a class="nav-link" asp-controller="eSpensa" asp-action="MyFood">My Food</a>
    <a class="nav-link" asp-controller="eSpensa" asp-action="MyLists">Shopping Lists</a>
</nav>

MiniProjekt/Views/eSpensa/AddItemToMyFood.cshtml
@model AddItemToMyFoodVM
@{
    ViewBag.Title = "Add new item";
}

<h3 class="display-5">Add Item</h3>

<form asp-controller="eSpensa" class="text-left">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="FoodGroup"></label>
        <select asp-for="FoodGroup" asp-items="Html.GetEnumSelectList<FoodGroupEnum>()" class="form-control">
            <option selected="selected" value="">Select food group</option>
        </select>
    </div>
    <div class="form-group date">
        <label asp-for="ExpirationDate"></label>
        <input asp-for="ExpirationDate" class="form-control" />
        <span asp-validation-for="ExpirationDate">
        </span>
    </div>
    <div class="form-check">
        <input asp-for="GoesInTheFridge" type="checkbox" class="form-check-input" />
        <label asp-for="GoesInTheFridge"></label>
    </div>
    <br/>
    <button asp-action="AddItemToMyFood" class="btn btn-primary">Add</button>
    <div asp-validation-summary="All"></div>
</form>

@section scriptsJq
    {
    @*<script src="/jquery/jquery.min.js"></script>*@
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.2/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>
}

MiniProjekt/Views/eSpensa/FoodList.cshtml
@model FoodListVM
@{
    ViewBag.Title = Model.Name;
}

<h3 class="display-5">@Model.Name</h3>
<ul>
    @{
        foreach (var food in Model.FoodsList)
        {
            <partial name="_FoodItemInMyFood" model=food />
        }
    }
</ul>

MiniProjekt/Views/eSpensa/Index.cshtml
@{
    ViewBag.Title = "Home";
}
@model IndexVM

<div class="text-left">
    <p>
        Welcome back <strong>Alessandro</strong>!
        <br />
        You have currently @Model.ExpiringSoon items expiring soon
        <br />
        You have currently @Model.InMyShoppingListCount items in your shopping list
    </p>
    <div>
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
</div>

MiniProjekt/Views/eSpensa/List.cshtml
@model ListVM
@{
    ViewBag.Title = Model.Name;
}

<h3 class="display-5">@Model.Name</h3>
<ul class="text-left">
    @{
        foreach (var food in Model.FoodsList)
        {
            <partial name="_FoodItemInShoppingList" model=food />
        }
    }
</ul>

MiniProjekt/Views/eSpensa/MyFood.cshtml
@{
    ViewBag.Title = "My Food";
}
@model MyFoodVM

<h3 class="display-5">My Food</h3>

<ul class="list-group list-group-numbered">
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">All my food</div>
            <span>
                <a asp-controller="eSpensa" asp-action="FoodList" asp-route-listName="All">View</a>
            </span>
        </div>
        <span class="badge bg-primary rounded-pill" style="color: white;">@Model.AllFoodCount</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">In my fridge</div>
            <span>
                <a asp-controller="eSpensa" asp-action="FoodList" asp-route-listName="Fridge">View</a>
            </span>
        </div>
        <span class="badge bg-primary rounded-pill" style="color: white;">@Model.ItemsInFridgeCount</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">In my pentry</div>
            <span>
                <a asp-controller="eSpensa" asp-action="FoodList" asp-route-listName="Pentry">View</a>
            </span>
        </div>
        <span class="badge bg-primary rounded-pill" style="color: white;">@Model.ItemsInPentryCount</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">Expiring Soon</div>
            <span>
                <a asp-controller="eSpensa" asp-action="FoodList" asp-route-listName="Expiring">View</a>
            </span>
        </div>
        <span class="badge bg-danger rounded-pill" style="color: white;">@Model.ConsumeSoon</span>
    </li>
</ul>

<a class="btn btn-primary mt-3" asp-action="AddItemToMyFood" role="button">Add New Item</a>

MiniProjekt/Views/eSpensa/MyLists.cshtml
@{
    ViewBag.Title = "My Lists";
}
@model MyListsVM

<h3 class="display-5">My Lists</h3>

<ul class ="list-group list-group-numbered">
    @{
        for (int i = 0; i < Model.ListOfLists.Length; i++)
        {
            <partial name="_ListItem" model=Model.ListOfLists[i]/>
        }
    }
</ul>